//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart_Application_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Shopping_CartEntities : DbContext
    {
        public Shopping_CartEntities()
            : base("name=Shopping_CartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressDetails> AddressDetails { get; set; }
        public virtual DbSet<Cart_Details> Cart_Details { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Product_Table> Products { get; set; }
        public virtual DbSet<RegisterUser> RegisterUser { get; set; }
        public virtual DbSet<SubCategories> SubCategories { get; set; }
    
        public virtual ObjectResult<usp_GetAllProdDetails_Result> usp_GetAllProdDetails(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllProdDetails_Result>("usp_GetAllProdDetails", userIDParameter);
        }
    
        public virtual ObjectResult<usp_GetCountries_Result> usp_GetCountries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCountries_Result>("usp_GetCountries");
        }
    
        public virtual ObjectResult<usp_GetStates_Result> usp_GetStates(Nullable<int> countryID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetStates_Result>("usp_GetStates", countryIDParameter);
        }
    }
}
