//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart_Application_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Shopping_CartEntities : DbContext
    {
        public Shopping_CartEntities()
            : base("name=Shopping_CartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressDetails> AddressDetails { get; set; }
        public virtual DbSet<Cart_Details> Cart_Details { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Product_Table> Products { get; set; }
        public virtual DbSet<RegisterUser> RegisterUser { get; set; }
        public virtual DbSet<SubCategories> SubCategories { get; set; }
    }
}
