//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart_Application_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAmounts
    {
        public int PaymentID { get; set; }
        public decimal Price { get; set; }
        public int Items { get; set; }
        public int DiscountPercentage { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal DeliveryCharges { get; set; }
        public decimal TotalAmount { get; set; }
        public int UserID { get; set; }
    
        public virtual RegisterUser RegisterUser { get; set; }
    }
}
