//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart_Application_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public int SR_NO { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product_Table Product_Table { get; set; }
        public virtual RegisterUser RegisterUser { get; set; }
    }
}
